Join the technological revolution that’s taking the financial world by storm. Mastering Bitcoin is your guide through the seemingly complex world of bitcoin, providing the knowledge you need to participate in the internet of money. Whether you’re building the next killer app, investing in a startup, or simply curious about the technology, this revised and expanded second edition provides essential detail to get you started.

Bitcoin, the first successful decentralized digital currency, is still in its early stages and yet it’s already spawned a multi-billion-dollar global economy open to anyone with the knowledge and passion to participate. Mastering Bitcoin provides the knowledge. You simply supply the passion.

The second edition includes:

* A broad introduction of bitcoin and its underlying blockchain—ideal for non-technical users, investors, and business executives
* An explanation of the technical foundations of bitcoin and cryptographic currencies for developers, engineers, and software and systems architects
* Details of the bitcoin decentralized network, peer-to-peer architecture, transaction lifecycle, and security principles
* New developments such as Segregated Witness, Payment Channels, and Lightning Network
* A deep dive into blockchain applications, including how to combine the building blocks offered by this platform into higher-level applications
* User stories, analogies, examples, and code snippets illustrating key technical concepts

====
The best-selling, highest rated and most cited book about how Bitcoin works. Used to teach about Bitcoin and Blockchains at top universities, Bitcoin startups, and inside terrified financial institutions.

"By far the best technical introduction to Bitcoin and cryptocurrencies"
====

This ebook is sold and delivered in three ebook formats: PDF, EPUB and MOBI/Kindle, without DRM restrictions, under a CC-BY-SA open license.
